"""empty message

Revision ID: b2a5458746f7
Revises: 
Create Date: 2025-07-15 08:42:43.770247

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b2a5458746f7'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id_mailaddress', sa.String(), nullable=False),
    sa.Column('login_pass', sa.String(length=128), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('school_year', sa.Integer(), nullable=False),
    sa.Column('course', sa.String(), nullable=False),
    sa.Column('hobby', sa.String(), nullable=False),
    sa.Column('sex', sa.Integer(), nullable=False),
    sa.Column('car', sa.String(), nullable=False),
    sa.Column('image', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id_mailaddress')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('users')
    # ### end Alembic commands ###
